### PR TITLE
Fixed Keycloak 'Getting Started' link

### PR DESCRIPTION
**Pull request by firthmj**
Another broken link fix

### CODE REVIEW

**Comment by garethsb** [comment]
An equivalent commit is also in previous PR #52 it looks like.

**Comment by firthmj** [comment]
It looks like PR #52 updated itself to include that commit - it didn't exist when I created the PR.

Seems it is part of my Github inexperience - I'm surprised PRs aren't fixed to a specific commit hash.

**Comment by jonathan-r-thorpe** [comment]
Already covered by #52

**Comment by garethsb** [comment]
> Seems it is part of my Github inexperience - I'm surprised PRs aren't fixed to a specific commit hash.

No worries, @firthmj ! That's right, PRs are associated with branches, so that you can deal with review comments, etc. simply by pushing more commits. (Of course this means you can also squash commits and rewrite history in other ways too, and _sometimes_ that's useful!)

**Pull request closed without merging**
